- .gitignore
- src/components/team-creation/PlayerSelectionModal.tsx
- src/components/team-creation/PositionCard.tsx
- src/components/team-creation/TableHeader.tsx
- src/components/team-creation/TeamActions.tsx
- src/components/team-creation/TeamFilter.tsx
- src/index.css
- src/screens/TeamCreationScreen.tsx
- src/services/leagueService.ts
- Sort by headers
- Filter by multiple teams
- Search Athletes
> Team Creation

- src/components/auth/CountrySelect.tsx
- src/components/profile/UserStatsGrid.tsx
- src/components/rankings/RankingsLeaderBoard.tsx
- src/components/rankings/UserRankingCard.tsx
- src/components/rankings/UserRankingFocusShort.tsx
- src/components/rankings/UserRankingsItem.tsx
- src/components/team-creation/TableHeader.tsx
- src/components/team-creation/player-selection-components/PlayerList.tsx
- src/hooks/useAuthUser.tsx
- src/screens/ProfileScreen.tsx
- src/screens/RankingsScreen.tsx
- src/screens/auth/SignUpScreen.tsx
- src/services/athleteService.ts
- src/services/userRankingsService.ts
- src/types/auth.ts
- src/types/countries.ts
- src/types/lucide-react.d.ts
- src/types/rugbyPlayer.ts
- src/types/userRanking.ts
this pull request adds user rankings page
> Feat  user rankings

- src/components/dashboard/ActiveLeaguesSection.tsx
- src/components/league/LeagueHeader.tsx
- src/screens/JoinLeagueScreen.tsx
- src/screens/LeagueScreen.tsx
- src/utils/leaguesUtils.ts
> hides leagues and adds join deadline

- src/components/players/PlayerCard.tsx
- src/components/players/profile/PlayerProfileHeaders.tsx
- src/components/players/profile/PlayerProfileSeasonStats.tsx
- src/components/profile/UserStatsGrid.tsx
- src/components/rankings/RankingsLeaderBoard.tsx
- src/components/rankings/UserRankingCard.tsx
- src/components/team-creation/TableHeader.tsx
- src/components/team-creation/player-selection-components/PlayerList.tsx
- src/hooks/useAsync.ts
- src/screens/PlayerProfileScreen.tsx
- src/screens/PlayersScreen.tsx
- src/services/athleteService.ts
- src/services/athleteSportsActions.ts
- src/types/lucide-react.d.ts
> Fix  get player by

- package.json
- pnpm-lock.yaml
- src/components/SideDrawer.tsx
- src/components/fixtures/FixtureHeadToHeadStats.tsx
- src/components/player/PlayerSmallCard.tsx
- src/components/shared/tabs/TabView.tsx
- src/components/team-creation/player-selection-components/usePlayersFilter.ts
- src/components/team/TeamStats.tsx
- src/hooks/useSmartBack.ts
- src/screens/FixtureScreen.tsx
- src/screens/LeagueScreen.tsx
- src/state/atom.factories.ts
Fixes issue with player first name being repeated and fixes back button on fixture stats page
- also adds indicators on match team stats tab view
> Fix  player names duplicated

- src/Routes.tsx
- src/components/dashboard/ActiveLeaguesSection.tsx
- src/components/dashboard/MyTeamsSection.tsx
- src/components/league/LeagueHeader.tsx
- src/components/league/LeagueStandings.tsx
- src/components/my-team/TeamActions.tsx
- src/components/my-team/TeamDataProvider.tsx
- src/components/my-team/TeamHeader.tsx
- src/components/team-creation/ReviewTeamModal.tsx
- src/screens/DashboardScreen.tsx
- src/screens/JoinLeagueScreen.tsx
- src/screens/LeagueScreen.tsx
- src/screens/MyTeamsScreen.tsx
- src/screens/ReviewTeamScreen.tsx
- src/screens/TeamCreationScreen.tsx
- src/services/leagueService.ts
- src/services/teamService.ts
this pull request adds a my team button to the league screen for easier navigation and also shows the league that a certain team card is belonging too
> Patch  my team btn

- src/components/SideDrawer.tsx
- src/components/dashboard/ActiveLeaguesSection.tsx
- src/components/leagues/LeagueCardDetailed.tsx
- src/components/team/TeamFormation.tsx
- src/components/team/TeamPlayerCard.tsx
- src/hooks/useAthletePointsBreakdown.ts
- src/screens/DashboardScreen.tsx
- src/screens/MyTeamScreen.tsx
- src/screens/ProfileScreen.tsx
- src/services/leagueService.ts
- src/types/fantasyLeague.ts
- src/types/fantasyTeamAthlete.ts
- src/types/lucide-react.d.ts
- src/types/rugbyPlayer.ts
> Fix  dashboard page

- src/components/league/LeagueHeader.tsx
- src/components/league/LeagueSettings.tsx
- src/components/league/LeagueStandings.tsx
- src/components/league/TeamAthletesModal.tsx
- src/components/league/useFantasyLeague.tsx
- src/components/leagues/LeagueGroupChat.tsx
- src/components/my-team/TeamHeader.tsx
- src/components/team/TeamStats.tsx
- src/contexts/FantasyLeagueContext.tsx
- src/data/messaging/messaging.utils.ts
- src/screens/LeagueScreen.tsx
- src/screens/MyTeamScreen.tsx
- src/types/fantasyLeague.ts
- src/types/league.ts
- src/utils/leaguesUtils.tsx
This pull request fixes a wierd issue that was causing the edit league button to show up when someone has a team there
> Feat  locking league

- src/components/leagues/LeagueLiveIndicator.tsx
- src/services/athleteService.ts
- src/types/lucide-react.d.ts
- src/types/sports_actions.ts
migrates from using sports action id to season id
> adds fix for undefined kick_off_time

- src/components/my-team/TeamDataProvider.tsx
- src/hooks/useAsync.ts
- src/screens/TeamCreationScreen.tsx
adds lock to user access team from my team screen
> adds lock to backdoor

- src/components/fixtures/FixtureCard.tsx
- src/components/leagues/LeagueCardDetailed.tsx
- src/components/leagues/league_dashboard_ui/LeagueCardFixturesSection.tsx
- src/components/rankings/RankingsLeaderBoard.tsx
- src/components/rankings/UserRankingCard.tsx
- src/components/rankings/UserRankingsItem.tsx
- src/components/team-creation/TeamCreationHeader.tsx
- src/services/athleteService.ts
- src/services/authService.ts
- src/services/leagueService.ts
- src/services/teamService.ts
- src/utils/backendUtils.ts
* adds fix
* removes lock
* adds fix
> Fix  api url (#30)

- src/components/leagues/LeagueGroupChat.tsx
- src/data/messaging/open_channel.init.ts
- src/data/messaging/school_boy_ruby.ts
- src/data/messaging/send_bird.init.ts
- src/hooks/useOpenChat.ts
- src/hooks/useSendbirdUser.tsx
- src/screens/SchoolBoyRugbyScreen.tsx
- src/services/logger.ts
> adds fix for SBR

- src/components/auth/post_sign_up/PickYourTeamCard.tsx
- src/components/auth/post_sign_up/PostSignUpDashboardButton.tsx
- src/components/auth/post_sign_up/PostSignUpTutorialButton.tsx
- src/components/auth/post_sign_up/PostSignUpViewLeaderBoardCard.tsx
- src/components/leagues/LeagueGroupChat.tsx
- src/components/leagues/LeagueLiveIndicator.tsx
- src/data/messaging/open_channel.init.ts
- src/data/messaging/school_boy_ruby.ts
- src/data/messaging/send_bird.init.ts
- src/hooks/useOpenChat.ts
- src/hooks/useSendbirdUser.tsx
- src/screens/PostSignUpWelcomeScreen.tsx
- src/screens/SchoolBoyRugbyScreen.tsx
- src/services/logger.ts
- src/utils/dateUtils.ts
- src/utils/leaguesUtils.tsx
- adds fixes for sign up flow and sets in up such that you are redirected to the correct page
> Fix  signup flow

- src/components/dashboard/HeroSection.tsx
- src/components/league/useFantasyLeague.tsx
- src/hooks/useRoter.ts
- src/screens/MyTeamsScreen.tsx
This pull request adds code to redirect user to the my team page when they have created a team for a certain round
> Fix  hero countdown

- src/Routes.tsx
- src/components/BottomNav.tsx
- src/components/sbr/SBRChatScreen.tsx
- src/components/sbr/SBRFixtures.tsx
- src/components/sbr/SbrContextSwitcher.tsx
- src/components/sbr/SbrFixtureCard.tsx
- src/components/sbr/SbrTeamLogo.tsx
- src/components/sbr/SbrVotingBallotBox.tsx
- src/components/sbr/SbrVotingModal.tsx
- src/components/sbr/SbrVotingModalNavigator.tsx
- src/components/sbr/SchoolBoyRugbyChat.tsx
- src/components/shared/DialogModal.tsx
- src/components/shared/VotingProgressBar.tsx
- src/components/shared/buttons/PrimaryButton.tsx
- src/hooks/useFxitureVotes.tsx
- src/hooks/useOpenChat.ts
- src/screens/PageView.tsx
- src/screens/SchoolBoyRugbyScreen.tsx
- src/services/logger.ts
- src/services/sbrService.ts
- src/types/lucide-react.d.ts
- src/types/sbr.ts
- tailwind.config.js
> Feat  sbr voting

- src/components/fixtures/FixtureHeadToHeadStats.tsx
- src/components/fixtures/FixtureScreenHeader.tsx
- src/components/fixtures/GroupedFixturesList.tsx
- src/components/sbr/SBRFixtures.tsx
- src/components/shared/BlueGradientCard.tsx
- src/components/shared/DialogModal.tsx
- src/screens/FixtureListScreen.tsx
- src/screens/FixtureScreen.tsx
- src/screens/PageView.tsx
- src/services/boxScoreService.ts
- src/utils/boxScoreUtils.ts
- src/utils/fixtureUtils.ts
* adds fixes to fixture page
* adds grouping to fixtures
* fixes fixure list page
* made fix to convertions stats
* ads fixes for fixture
> Fix  fixture page (#44)

- src/components/leagues/league_dashboard_ui/LeagueCardMyTeamSection.tsx
- src/components/my-team/TeamHeader.tsx
- src/components/player/profile-modal-components/PlayerInfo.tsx
- src/components/player/profile-modal-components/usePlayerStats.ts
- src/services/athleteService.ts
This push adds a fix for the athlete profile modal showing 0s
> 47 athletes stats modal showing 0s

- src/components/leagues/league_dashboard_ui/LeagueCardMyTeamSection.tsx
- src/components/my-team/TeamHeader.tsx
- src/components/player/profile-modal-components/PlayerInfo.tsx
- src/components/player/profile-modal-components/usePlayerStats.ts
- src/services/athleteService.ts
* adds z to player info sticky
* made fix for athlete modal
> 47 athletes stats modal showing 0s (#48)

- src/components/sbr/SbrFixtureCard.tsx
- src/components/sbr/fixtures/SBRFixtures.tsx
- src/components/sbr/voting/SbrPersonalVotingSummary.tsx
- src/components/sbr/voting/SbrVotingBallotBox.tsx
- src/components/sbr/voting/SbrVotingModal.tsx
- src/screens/SchoolBoyRugbyScreen.tsx
- src/utils/sbrUtils.ts
> Feat  round 1 sbr update

- src/components/sbr/SbrFixtureCard.tsx
- src/components/sbr/fixtures/SBRFixtures.tsx
- src/components/sbr/voting/SbrPersonalVotingSummary.tsx
- src/components/sbr/voting/SbrVotingBallotBox.tsx
- src/components/sbr/voting/SbrVotingModal.tsx
- src/screens/SchoolBoyRugbyScreen.tsx
- src/utils/sbrUtils.ts
* adds scores to SBR
* adds update to matches
* adds right and wrong indicator to voting modal
* adds sbr fixtures and scores
* adds some name fixes
> Feat  round 1 sbr update (#56)

- src/components/BottomNav.tsx
- src/components/SideDrawer.tsx
- src/components/dashboard/HeroSection.tsx
- src/components/dashboard/UpcomingFixturesSection.tsx
- src/components/fixtures/FixtureCard.tsx
- src/components/fixtures/FixtureRosterList.tsx
- src/components/fixtures/FixtureRosters.tsx
- src/components/fixtures/FixtureScreenHeader.tsx
- src/components/fixtures/GroupedFixturesList.tsx
- src/components/league/FixturesList.tsx
- src/components/leagues/JoinLeagueDeadlineContdown.tsx
- src/components/my-team/TeamTabsContent.tsx
- src/components/shared/RugbyPitch.tsx
- src/components/shared/TabButton.tsx
- src/components/shared/WarningCard.tsx
- src/components/shared/tabs/TabView.tsx
- src/components/team/AthletesAvailabilityWarning.tsx
- src/components/team/TeamFormation.tsx
- src/components/team/TeamPlayerCard.tsx
- src/hooks/useRoter.ts
- src/screens/FixtureListScreen.tsx
- src/screens/FixtureScreen.tsx
- src/screens/LeagueScreen.tsx
- src/screens/MyTeamScreen.tsx
- src/services/gamesService.ts
- src/types/fantasyTeamAthlete.ts
- src/types/games.ts
- src/types/team.ts
Adds the following:
- adds a venue
- adds lineups to matches
> 63 add venue to fixtures

- src/components/BottomNav.tsx
- src/components/SideDrawer.tsx
- src/components/dashboard/HeroSection.tsx
- src/components/dashboard/UpcomingFixturesSection.tsx
- src/components/fixtures/FixtureCard.tsx
- src/components/fixtures/FixtureRosterList.tsx
- src/components/fixtures/FixtureRosters.tsx
- src/components/fixtures/FixtureScreenHeader.tsx
- src/components/fixtures/GroupedFixturesList.tsx
- src/components/league/FixturesList.tsx
- src/components/leagues/JoinLeagueDeadlineContdown.tsx
- src/components/my-team/TeamTabsContent.tsx
- src/components/shared/RugbyPitch.tsx
- src/components/shared/TabButton.tsx
- src/components/shared/WarningCard.tsx
- src/components/shared/tabs/TabView.tsx
- src/components/team/AthletesAvailabilityWarning.tsx
- src/components/team/TeamFormation.tsx
- src/components/team/TeamPlayerCard.tsx
- src/hooks/useRoter.ts
- src/screens/FixtureListScreen.tsx
- src/screens/FixtureScreen.tsx
- src/screens/LeagueScreen.tsx
- src/screens/MyTeamScreen.tsx
- src/services/gamesService.ts
- src/types/fantasyTeamAthlete.ts
- src/types/games.ts
- src/types/team.ts
* makes cards clickable
* adds venue to grouped fxitres
* adds indicator for game that the athlete is playing
* adds warning card component
* swap my teams and fixtures
* adds rugby pitch component
* adds class name to warning card
* adds types to plyaer
* adds athlete availability warning component
* adds fixes to wording and english
* adds roster tab
> 63 add venue to fixtures (#66)

- src/components/fixtures/FixtureRosters.tsx
- src/components/shared/WarningPopup.tsx
- src/components/team-creation/player-selection-components/PlayerList.tsx
- src/components/team-creation/player-selection-components/PlayerListItem.tsx
- src/components/team-creation/player-selection-components/usePlayersFilter.ts
- src/hooks/useClickOutside.ts
Adds fix for player profile confusion
> 61 fix player budget modal confusion

- src/components/settings/SettingsModal.tsx
- src/components/settings/UserNotificationsSettings.tsx
- src/screens/ProfileScreen.tsx
- src/services/authService.ts
- src/services/notificationsService.ts
- src/types/auth.ts
- src/types/lucide-react.d.ts
- src/types/notifications.ts
Adds Ui to chose the type of settings preference the user wants to have set
> 69 add notification preferences

- src/components/my-team/list/MyTeamListCard.tsx
- src/components/shared/PillTap.tsx
- src/components/shared/PlayerMugshot.tsx
- src/screens/MyTeamsScreen.tsx
- src/types/cardTiers.ts
- adds team faces to my teams list screen
> 128 show team faces on my teams page

- src/screens/auth/AuthChoiceScreen.tsx
- src/screens/auth/SignInScreen.tsx
- src/screens/auth/WelcomeScreen.tsx
> Patch  disable social login

- src/App.tsx
- src/components/dashboard/FeaturedPlayersCarousel.tsx
- src/components/dashboard/HeroSection.tsx
- src/components/dashboard/UpcomingFixturesSection.tsx
- src/components/network/NetworkStatusProvider.tsx
- src/screens/DashboardScreen.tsx
- src/screens/SeasonScreen.tsx
- src/screens/auth/SignInScreen.tsx
- src/screens/auth/SignUpScreen.tsx
- src/types/lucide-react.d.ts
- src/utils/backendUtils.ts
- this pull request improves authentication issues we have in the app
> Fix Authentication Issues

- src/components/fantasy-league/LeagueFixturesTab.tsx
- src/components/fantasy-league/LeagueStandings.tsx
- src/components/fantasy-league/buttons/JoinLeagueButton.tsx
- src/components/fantasy-league/commissioner/LeagueCommissionerTab.tsx
- src/components/fantasy-leagues/join_league_screen/MyLeaguesTab.tsx
- src/components/fantasy-leagues/ui/LeagueVisibilityInput.tsx
- src/components/shared/tabs/TabView.tsx
- src/hooks/leagues/useFantasyLeagueGroup.tsx
- src/screens/LeagueScreen.tsx
- src/services/fantasy/fantasyLeagueGroupsService.ts
- src/services/leagueService.ts
- src/types/fantasyLeague.ts
- src/types/fantasyLeagueGroups.ts
- src/utils/swrKeys.ts
- adds league commissioner feature to fantasy group screen
> Feat  league commissioner

- src/components/fantasy-league/LeagueStandings.tsx
- src/services/fantasy/fantasyLeagueGroupsService.ts
- src/types/fantasyLeagueGroups.ts
- adds calculation api for league standings list
> League Standings List

- src/App.tsx
- src/components/fantasy-league/LeagueStandings.tsx
- src/components/player/profile-modal-components/tabs/PlayerOverviewTab.tsx
- src/components/player/profile-modal-components/usePlayerStats.ts
- src/components/players/compare/PlayerCompareItem.tsx
- src/components/stats/SportActionsDefinitionsProvider.tsx
- src/services/athletes/djangoAthletesService.ts
- src/services/sportActionsService.ts
- src/state/comparePlayers.atoms.ts
- src/state/sportActions.atoms.ts
- src/types/sports_actions.ts
- src/utils/athleteUtils.ts
- src/utils/swrKeys.ts
- adds fix for player compare modal on new opta stuff
> Fix Player Compare Modal

- package.json
- pnpm-lock.yaml
- src/Routes.tsx
- src/components/fantasy-leagues/UserCreatedLeaguesSection.tsx
- src/components/network/NetworkStatusProvider.tsx
- src/hooks/leagues/useShareLeague.tsx
- src/screens/onboarding/InviteStepsScreen.tsx
- src/types/constants.ts
- adds screen with steps for inviting other users
- fixes share api and adds more information to it
> Patch  inviting players

- src/components/fixtures/FixtureAthleteStats.tsx
- src/components/fixtures/FixtureSearchResults.tsx
- src/components/fixtures/PlayerFixtureStatsModal.tsx
- src/screens/FixtureScreen.tsx
- src/services/boxScoreService.ts
- src/types/boxScore.ts
- merges athlete sport actions
> Patch  athlete sports actions

- src/components/dashboard/my-team/LeagueOverviewCard.tsx
- src/components/match_center/ProMatchCenter.tsx
- src/hooks/leagues/useShareLeague.tsx
- src/hooks/useCountdown.ts
- fixes negative countdown issue
- live fixtures on past fixtures
- sanitising share url
> Fix  negative countdown

- src/components/Header.tsx
- src/components/auth/AuthLayout.tsx
- src/components/auth/guest/ClaimAccountNoticeCard.tsx
- src/components/auth/login/GuestLoginBox.tsx
- src/components/branding/BetaTag.tsx
- src/components/dashboard/my-team/LeagueOverviewCard.tsx
- src/components/fantasy-league/LeagueCountdown.tsx
- src/components/fantasy-league/standings/LeagueStandingsTable.tsx
- src/components/settings/QaNoticeCard.tsx
- src/hooks/fantasy/useLeagueRoundStandingsFilter.ts
- src/hooks/leagues/useFantasyLeagueGroup.tsx
- src/hooks/useDeviceId.tsx
- src/screens/LeagueScreen.tsx
- src/screens/UserProfileScreen.tsx
- src/screens/auth/SignInScreen.tsx
- src/screens/auth/WelcomeScreen.tsx
- src/services/authService.ts
- src/types/device.ts
- src/types/lucide-react.d.ts
- src/utils/deviceId/deviceIdUtils.ts
- src/utils/deviceId/exceptions.ts
- src/utils/deviceId/mobileDeviceIdUtils.ts
- src/utils/deviceId/webDeviceIdUtils.ts
- src/utils/standingsUtils.ts
- src/utils/webUtils.ts
- adds way to toggle between weeks that you want to filter by
- fixes issue with countdown in the app
- creates two auth implementations, one for production and one for dev
- reactors deviceId code into different functions
- adds tag for qa app
> League UI Improvements

- src/components/fantasy-league/overview/LeagueOverviewTab.tsx
- src/components/fantasy-league/overview/LeagueRoundFixturesOverview.tsx
- src/components/fantasy-league/overview/UserRoundOverviewCard.tsx
- src/components/fantasy-league/overview/UserRoundScoringUpdate.tsx
- src/components/fantasy-league/overview/UserTeamOverview.tsx
- src/components/fantasy-league/team-modal/team_overview/TeamOverviewView.tsx
- src/components/fixtures/SmallFixtureCard.tsx
- src/components/shared/buttons/PrimaryButton.tsx
- src/screens/LeagueScreen.tsx
- src/types/fantasyLeague.ts
- src/types/lucide-react.d.ts
- src/utils/fixtureUtils.ts
> Feat league overview tab

- src/components/dashboard/my-team/LeagueOverviewCard.tsx
- src/screens/DashboardScreen.tsx
- adjusts spacing and text for mobile
> Feat  dashboard v3.0

- src/components/fantasy-leagues/MyTeams.tsx
- src/components/fantasy-leagues/my-team/EditableTeamSlotItem.tsx
- src/components/fantasy-leagues/my-team/FantasyLeagueTeamProvider.tsx
- src/components/fantasy-leagues/my-team/MyTeamEditView.tsx
- src/components/fantasy-leagues/my-team/MyTeamPitchView.tsx
- src/components/fantasy-leagues/my-team/MyTeamStateProvider.tsx
- src/components/fantasy-leagues/my-team/SaveTeamBar.tsx
- src/components/fantasy-leagues/my-team/ViewMyTeam.tsx
- src/components/player/PlayerGameCard.tsx
- src/components/team-creation/PlayerSelectionModal.tsx
- src/components/team/TeamFormation.tsx
- src/services/fantasy/fantasyAthleteService.ts
- src/state/fantasy/fantasyLeagueTeam.atoms.ts
- src/state/fantasy/myTeam.atoms.ts
- src/types/athletes.ts
- src/types/fantasy/myTeam.ts
- src/types/fantasyLeagueTeam.ts
- src/types/fantasyTeamAthlete.ts
- src/utils/athleteUtils.ts
- adds remove button to allow a user to remove multiple players at once
- UI to handle empty slots
> Feat  remove player without swap

- src/components/fantasy-league/LeagueInfoTab.tsx
- src/components/fantasy-league/LeagueStandings.tsx
- src/components/fantasy-league/overview/LeagueOverviewTab.tsx
- src/components/fantasy-leagues/MyTeams.tsx
- src/components/fantasy-leagues/my-team/EditableTeamSlotItem.tsx
- src/components/fantasy-leagues/my-team/MyTeamEditView.tsx
- src/components/fantasy-leagues/my-team/MyTeamPitchView.tsx
- src/components/fantasy-leagues/my-team/SaveTeamBar.tsx
- src/hooks/fantasy/useLeagueRoundStandingsFilter.ts
- src/screens/LeagueScreen.tsx
- src/services/analytics/fantasyAnalytics.ts
- adds UI changes for when a league is locked, like blocking team editing
- adds analytics for fantasy league screen
> Fix  editing locked round

- src/components/Header.tsx
- src/components/dashboard/HeroSection.tsx
- src/components/dashboard/UpcomingFixturesSection.tsx
- src/components/dashboard/my-team/LeagueOverviewCard.tsx
- src/components/fantasy-leagues/join_league_screen/showcase_section/ShowcaseLeagueSection.tsx
- src/components/fantasy-seasons/FantasySeasonDashboard.tsx
- src/components/fantasy-seasons/FantasySeasonSelector.tsx
- src/components/shared/ScrummyMatrixBackground.tsx
- src/screens/DashboardScreen.tsx
- src/screens/FeaturedFantasyLeagueGroups.tsx
- src/services/fantasy/fantasyLeagueGroupsService.ts
- src/services/notifications/inAppMessagesService.ts
- src/types/notifications/inAppMessage.ts
> Feat  in app messages

- src/components/fantasy-leagues/CreateMyTeam.tsx
- src/components/player-picker/PlayerPickerDataProvider.tsx
- src/components/player-picker/PlayerPickerHeader.tsx
- src/components/player-picker/PlayerPickerPlayerList.tsx
- src/components/player-picker/PlayerPickerV2.tsx
- src/components/team-creation/player-selection-components/SearchBar.tsx
- src/hooks/playerPicker/usePlayerPicker.ts
- src/screens/FeaturedFantasyLeagueGroups.tsx
- src/state/playerPicker/playerPicker.ts
- src/utils/athleteUtils.ts
- src/utils/fantasy/leagueGroupsUtils.ts
- fixes search issue
- adds back WWC to home page
> Patch  30 sep 2025
